### ISSUE TITLE
iPad wird nicht als mobilgerät erkannt

### ISSUE THREAD

**Issue by joshinils** [JDAPweb/WA-project#106]
soll es zwar nicht, aber so wie das layout aussieht, macht das nur sinn:

![bild von ios 1](https://user-images.githubusercontent.com/34302971/42780321-28cd9252-8943-11e8-8676-fc830214843e.jpg)
![bild von ios](https://user-images.githubusercontent.com/34302971/42780322-28f0b80e-8943-11e8-94b2-d7d2ec8d018d.jpg)
![bild von ios 3](https://user-images.githubusercontent.com/34302971/42780323-2914dd10-8943-11e8-9e2d-58cd55b709cb.jpg)
![bild von ios 2](https://user-images.githubusercontent.com/34302971/42780324-293418a6-8943-11e8-8a99-b951273a289a.jpg)

**Comment by philsupertramp** [comment]
wird verschoben in backlog als evtl feature
