### ISSUE TITLE
DB-Modell: Votingsystem

### ISSUE THREAD

**Issue by philsupertramp** [JDAPweb/WA-project#14]
Es wird ein Votingsystem benötigt.
Sinn: Ranking der Fragen besser beinflussen und den Usern die Möglichkeit geben ihre Meinung über Fragen und Antworten abzugeben.

Dafür muss sowohl an die Fragentabelle `t_question` als auch an `t_answer` 2 neue Spalten hinzugefügt werden, `upvotes` und `downvotes`. Das Endergebnis lässt sich dann durch deren Differenz berechnen, ist also nicht nötig hart gecoded vorhanden zu sein.

**Comment by joshinils** [comment]
das ranking kann jeweils anders berechnet werden abhängig der vorliebe der sortierung, nach datum, nach absoluten votes (up-down) oder "hot" [ein mix aus den dreien](https://cdn-images-1.medium.com/max/1600/0*21Ezm5SbYie_a3oD.png), kontrovers, also |up-down|<eps, d.h. etwa gleich viele up wie down, aber jeweils viele. und jeweils auf einen zeitraum beschränkt

**Comment by philsupertramp** [comment]
Meinte hiermit eigentlich nur 2 Spalten `upvote` und `downvote` um Anhaltspunkte zu bekommen, wie die Punkte vergeben werden sollten wir uns dann noch überlegen.
