### ISSUE TITLE
Debugging hängt noch in master Branch

### ISSUE THREAD

**Issue by philsupertramp** [JDAPweb/WA-project#147]
"Debugging" echos hängen noch in `detail.php`
![bubu](https://user-images.githubusercontent.com/9550040/43016725-099dc2da-8c54-11e8-9385-0d531a54e11f.png)

**Comment by joshinils** [comment]
BUBUBU
	ja, weil das noch nich fertig ist
BUBUBU

**Comment by joshinils** [comment]
aber du kannst das ja auch so umschreiben, dass der else fall nicht notwendig ist, oder?

**Comment by philsupertramp** [comment]
Ja, mach ich!
