### ISSUE TITLE
[formatierung falsch] HTML/CSS: Antwort gegeben?

### ISSUE THREAD

**Issue by philsupertramp** [JDAPweb/WA-project#16]
Bei der Auflistung der Fragen fehlt noch die Markierung, dass eine Frage beantwortet wurde.

**Comment by joshinils** [comment]
ja, da hast du wohl recht

**Comment by joshinils** [comment]
ich glaub das fragezeochen aus dem logo mit nem leicht roten hintergrund rechts daneben, als auch das ausrufezeichen mit leicht grün könnten da gut gehen

**Comment by philsupertramp** [comment]
das klingt gut! 
hast du da ne Vorlage, oder soll ich mal schauen?

**Comment by joshinils** [comment]
ich weiß nich wie ich die 4 dinger links mit dem bild vereinen soll, so dass das bild nich nach unten herausragt. also so, dasss die höhe des bildes (mit padding, klar) auf die höhe der 2 divs links davon limitiert ist

**Comment by philsupertramp** [comment]
closed durch  #83
