### ISSUE TITLE
error 404 requested content not found

### ISSUE THREAD

**Issue by joshinils** [JDAPweb/WA-project#23]
falls was angefragt wird, das nicht existiert, soll dies hier angezeigt werden

**Comment by philsupertramp** [comment]
Muss für User und Posts noch eingebaut werden

- [ ] User

- [ ]  Posts

**Comment by joshinils** [comment]
also mach ich einfach ne 404 seite auf die dann verlinkt wird oder dort importiert? oder braucht man zwei verschiedene?

**Comment by philsupertramp** [comment]
Genau!

**Comment by philsupertramp** [comment]
Kann das dann aber unter PHP weiter führen, sobald die 404 da ist :grin:

**Comment by joshinils** [comment]
[ok, ist da](http://pc18.beuth-hochschule.de/php/sose18/gruppe6/blabla)
