### ISSUE TITLE
registrierseite

### ISSUE THREAD

**Issue by joshinils** [JDAPweb/WA-project#28]
zum neuen benutzer erstellen

@philsupertramp welche sachen/elemente sind benötigt dafür?

**Comment by philsupertramp** [comment]
Emailadresse | Passwort | Nutzername

**Comment by philsupertramp** [comment]
vorerst closed #81

**Comment by joshinils** [comment]
@philsupertramp ist das nicht schon fertig? bei widerspruch begründet wiederöffnen
