### ISSUE TITLE
Frageseite

### ISSUE THREAD

**Issue by joshinils** [JDAPweb/WA-project#37]
(am besten `detail.php`, sodass der Link dann auf `/detail.php?question=[question_id]` endet)
- Antwortformular

**Comment by joshinils** [comment]
das hab ich jetzt statisch schon mit lorem erstellt. fehlt noch das interaktiv zu füllen

**Comment by philsupertramp** [comment]
Thx, bin dran!

**Comment by philsupertramp** [comment]
Jetzt fehlen "nur" noch die Formulare + die richtige Makierung wenn eine Frage beantwortet ist.

**Comment by philsupertramp** [comment]
einziger Punkt der noch Fehlt: Antwort markieren.
