### ISSUE TITLE
Dokumentation beginnen

### ISSUE THREAD

**Issue by philsupertramp** [JDAPweb/WA-project#4]

**Comment by joshinils** [comment]
Die Projektdokumentation muss enthalten:
- den Quellcode
- eine detaillierte Beschreibung, welches Projektmitglied welchen Teil der Webseite erzeugt hat
- eine Abschlusspräsentation
- ein Projekttagebuch (Protokoll über die Entwicklung) - im moodle Wiki
- eine Auswertung enthalten, ob der Projektplan umgesetzt wurde Begründungen für eventuelle Abweichungen
Das Projekttagebuch und die Auswertung gehen inhaltlich nicht in die Bewertung ein

**Comment by joshinils** [comment]
bis wann muss das fertig sein?

**Comment by philsupertramp** [comment]
Bis spätestens zur Abgabe, würde aber sagen dass wir sie währenddessen schreiben. Schau mich mal nach einer Möglichkeit wie [phpDocs](https://www.phpdoc.org/)

**Comment by philsupertramp** [comment]
Interpreter für Markdown und LaTeX https://github.com/codeassign/markjax

**Comment by philsupertramp** [comment]
sollte doch fertig sein, richtig? > - 
<sub>[View in Slack](https://pandph.slack.com/archives/GBA7K36R2/p1533290792000058)</sub>
