### ISSUE TITLE
profil.php

### ISSUE THREAD

**Issue by joshinils** [JDAPweb/WA-project#49]
ohne parameter sieht das seltsam aus, wenn  man nicht angemeldet ist

**Comment by joshinils** [comment]
auch wenn man angemeldet ist!

**Comment by philsupertramp** [comment]
![profile](https://user-images.githubusercontent.com/9550040/42727152-93d98e6e-87a1-11e8-8996-4d6cdece3d04.png)

**Comment by philsupertramp** [comment]
closed in #82
