### ISSUE TITLE
bewertungsknöpfe/pfeile

### ISSUE THREAD

**Issue by joshinils** [JDAPweb/WA-project#50]
die pfeile für die bewertung müssen noch zu interaktiven knöpfen werden

**Comment by philsupertramp** [comment]
würde dabei dann bei den momentanen Symbolen bleiben
wichtig! Die Symbole brauchen dann: `style="text-decoration: none;"` :wink:

**Comment by joshinils** [comment]
auch auf top natürlich

**Comment by philsupertramp** [comment]
Nur kurz als Verständnisfrage, wieso auf top auch?

**Comment by joshinils** [comment]
naja, wenn ich mir das ansehe möchte ich ja vielleicht sachen einfach bewerten ohne sie weiter zu lesen.

auf reddit kann man zb einstellen, dass downvoted nicht mehr angezeigt wird bei refresh
