### ISSUE TITLE
chrome php fehler

### ISSUE THREAD

**Issue by joshinils** [JDAPweb/WA-project#79]
[hier](http://localhost/git/detail.php?question=2)

[chrome](https://pandph.slack.com/files/UA42U89RN/FBPUZD3DW/chrome.png)
in firefox passiert das nicht

**Comment by philsupertramp** [comment]
fürs archiv
![chrome](https://user-images.githubusercontent.com/9550040/42774587-5b3468d0-8932-11e8-8c0b-33b40b108577.PNG)

**Comment by joshinils** [comment]
dasselbe auch auf dem iPhone:

![bild von ios](https://user-images.githubusercontent.com/34302971/42780365-4d1360d8-8943-11e8-9063-3dc7e3f9cfd9.png)

**Comment by joshinils** [comment]
es scheint wohl so, als würde firefox das besser hinkriegen, oder verheimlichen/unterdrücken

**Comment by joshinils** [comment]
duplicated by #108
